### ISSUE TITLE
[3pt]  - Create feature: add  new like - Student A

### ISSUE THREAD

**Issue by Javed-Shahbaz** [Javed-Shahbaz/JavaScript-Capstone#9]
When the user clicks on the Like button of an item (on Homepage), the interaction is recorded in the Involvement API and the screen is updated.

**Comment by LarryIVC** [comment]
Hi, @Javed-Shahbaz I create a new PR for this issue, please review it.

https://github.com/Javed-Shahbaz/JavaScript-Capstone/pull/26
